import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Q1() {
  return (
    <div className={styles.container}>
      <Head>
        <title>test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Hi! I'm a Question and I have lots of thoughts</h1>
    </div>
  )
}
