import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Q1 from '../components/q1'
import Q2 from '../components/q2'
import Q3 from '../components/q3'
import Slide from 'react-reveal/Slide';
import {useState} from 'react'
import IconButton from '@mui/material/IconButton';
import Grid from '@mui/material/Grid';
import KeyboardArrowLeftIcon from '@mui/icons-material/KeyboardArrowLeft';
import KeyboardArrowRightIcon from '@mui/icons-material/KeyboardArrowRight';

export default function Section1() {
    const [questionCounter, _setQuestionCounter] = useState(1);
    const [appearFromLeft, setAppearFromLeft] = useState(true);
    const nextQuestion = () => {_setQuestionCounter(questionCounter + 1); setAppearFromLeft(true)}
    const previousQuestion = () => {_setQuestionCounter(questionCounter - 1); setAppearFromLeft(false)}

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <Grid container spacing={2}>
        <Grid item xs={1}>
            <IconButton aria-label="previous question" onClick={previousQuestion} disabled={questionCounter <= 1} size="large">
                <KeyboardArrowLeftIcon />
            </IconButton>
        </Grid>
        <Grid item xs={10}>
        <Slide left={appearFromLeft} right={!appearFromLeft} opposite collapse when={questionCounter == 1}>
            <Q1/>
        </Slide>
        <Slide left={appearFromLeft} right={!appearFromLeft}  opposite collapse when={questionCounter == 2}>
            <Q2/>
        </Slide>
        <Slide left={appearFromLeft} right={!appearFromLeft}  opposite collapse when={questionCounter == 3}>
            <Q3/>
        </Slide>
        </Grid>
        <Grid item xs={1}>
            <IconButton aria-label="next question" onClick={nextQuestion} disabled={questionCounter >= 3} size="large">
                <KeyboardArrowRightIcon />
            </IconButton>
        </Grid>
        </Grid>
        </main>
    </div>
  )
}
